# Generated by Django 5.1.1 on 2024-10-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
