# Generated by Django 5.1.1 on 2024-10-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_stocktransaction_user_portfolio_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
