# Generated by Django 5.1.1 on 2024-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
