# Generated by Django 5.1.1 on 2024-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_portfolio_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='threshold',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
