# Generated by Django 5.1.1 on 2024-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_portfolio_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='threshold',
            new_name='BUY_threshold',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='SELL_threshold',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
