# Generated by Django 5.1.1 on 2024-11-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_threshold_portfolio_buy_threshold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='BUY_threshold',
            new_name='threshold',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='SELL_threshold',
        ),
    ]
